/* ZOVA — lightweight interactions: mobile nav + scroll reveal */
(function () {
  "use strict";

  var copy = {
    en: {nav:["Features","How it Works","Learn","Screenshots","Privacy","Support"], heroKicker:"AI-powered classroom assistance for Chrome", heroTitle:"Understand every class.|In your language.", heroLead:"Follow online lessons with live transcription, translation, optional translated audio, classroom explanations and saved study notes — directly in your browser.", heroNote:"Zova is 100% free to use. Google API limits or terms may apply separately.", add:"Add to Chrome", how:"See how Zova works"},
    de: {nav:["Funktionen","So funktioniert es","Anleitung","Screenshots","Datenschutz","Support"], heroKicker:"KI-Unterstützung für den Unterricht in Chrome", heroTitle:"Verstehe jeden Unterricht.|In deiner Sprache.", heroLead:"Folge Online-Unterricht mit Live-Transkription, Übersetzung, optionalem Audio, Erklärungen und gespeicherten Lernnotizen — direkt im Browser.", heroNote:"Zova ist 100 % kostenlos. Für Google-API können eigene Limits oder Bedingungen gelten.", add:"Zu Chrome hinzufügen", how:"So funktioniert Zova"},
    zh: {nav:["功能","使用方法","指南","截图","隐私","支持"], heroKicker:"Chrome 智能课堂助手", heroTitle:"理解每一堂课。|用你的语言学习。", heroLead:"通过实时转录、翻译、可选语音、课堂解释和学习笔记，直接在浏览器中跟上在线课程。", heroNote:"Zova 完全免费。Google API 可能有单独的限制或条款。", add:"添加到 Chrome", how:"了解 Zova 的工作方式"},
    hi: {nav:["सुविधाएँ","कैसे काम करता है","गाइड","स्क्रीनशॉट","गोपनीयता","सहायता"], heroKicker:"Chrome के लिए AI कक्षा सहायक", heroTitle:"हर कक्षा को बेहतर समझें।|अपनी भाषा में।", heroLead:"लाइव ट्रांसक्रिप्शन, अनुवाद, वैकल्पिक ऑडियो, कक्षा स्पष्टीकरण और सेव किए गए नोट्स के साथ ऑनलाइन पाठों को ब्राउज़र में समझें।", heroNote:"Zova 100% मुफ़्त है। Google API की अपनी सीमाएँ या शर्तें हो सकती हैं।", add:"Chrome में जोड़ें", how:"Zova कैसे काम करता है"}
  };
  var languages = [["en","English"],["de","Deutsch"],["zh","中文（简体）"],["hi","हिन्दी"],["ar","العربية"],["es","Español"],["fr","Français"],["it","Italiano"],["pt","Português"],["ja","日本語"],["ko","한국어"],["ru","Русский"],["tr","Türkçe"],["nl","Nederlands"],["pl","Polski"],["uk","Українська"],["vi","Tiếng Việt"],["id","Bahasa Indonesia"],["th","ไทย"],["he","עברית"],["fa","فارسی"],["ur","اردو"],["bn","বাংলা"],["ta","தமிழ்"],["te","తెలుగు"],["mr","मराठी"],["gu","ગુજરાતી"],["kn","ಕನ್ನಡ"],["ml","മലയാളം"],["pa","ਪੰਜਾਬੀ"],["sw","Kiswahili"],["am","አማርኛ"],["yo","Yorùbá"],["ig","Igbo"],["ha","Hausa"],["zu","isiZulu"],["af","Afrikaans"],["sq","Shqip"],["hy","Հայերեն"],["az","Azərbaycan"],["eu","Euskara"],["be","Беларуская"],["bs","Bosanski"],["bg","Български"],["ca","Català"],["hr","Hrvatski"],["cs","Čeština"],["da","Dansk"],["et","Eesti"],["fi","Suomi"],["gl","Galego"],["ka","ქართული"],["el","Ελληνικά"],["hu","Magyar"],["is","Íslenska"],["ga","Gaeilge"],["lv","Latviešu"],["lt","Lietuvių"],["mk","Македонски"],["ms","Melayu"],["mt","Malti"],["no","Norsk"],["ro","Română"],["sr","Српски"],["sk","Slovenčina"],["sl","Slovenščina"],["so","Soomaali"],["sv","Svenska"],["tl","Filipino"],["cy","Cymraeg"],["xh","isiXhosa"],["km","ខ្មែរ"],["lo","ລາວ"],["my","မြန်မာ"],["ne","नेपाली"],["si","සිංහල"],["uz","O‘zbekcha"],["ps","پښتو"]];
  copy.ui = {
    en:{"features.eyebrow":"Features","features.title":"Everything you need to keep up with every lesson.","features.lead":"Zova works beside the lesson you're watching — transcribing, translating and helping you study without leaving the page.","live.title":"Follow every lesson live","live.description":"Turn the lesson you're watching into a readable, live transcript — with translation and optional spoken audio.","assist.title":"Understand difficult content","assist.description":"Stuck on a concept? Ask for a focused explanation, a direct answer or a concise summary built from recent lesson context.","notes.title":"Keep good notes","notes.description":"Capture what matters with Smart Notes and save the whole session for later study.","dashboard.title":"Review & manage your lessons","dashboard.description":"Everything you save lives in one local Dashboard — search, review, follow the learning structure and export from a single place.","how.eyebrow":"How it works","how.title":"From a live lesson to saved study notes.","how.lead":"Two simple paths — one for following the lesson, one for understanding it.","learning.eyebrow":"From class to learning","learning.title":"Turn classroom context into a path you can follow.","learning.lead":"A transcript records what was said. Zova can organize saved classroom evidence into a focused learning structure, so you can review the material progressively.","learning.savedTitle":"Saved Class","learning.savedDescription":"Keep the transcript, translation, Smart Notes and relevant study content together in local class history.","learning.graphTitle":"Learning Graph","learning.graphDescription":"Organize the lesson as chapters, topics and concepts—not one node for every spoken sentence.","learning.detailTitle":"Study Detail","learning.detailDescription":"Open a guided learning unit for a selected concept, with the lesson context that gives it meaning.","learning.reviewTitle":"Progressive Review","learning.reviewDescription":"Start with the core idea and key points, then explore examples, common mistakes, Quick Check and deeper detail when useful."},
    de:{"features.eyebrow":"Funktionen","features.title":"Alles, was du für jede Unterrichtsstunde brauchst.","features.lead":"Zova arbeitet neben deiner Lektion — für Transkription, Übersetzung und Lernen ohne die Seite zu verlassen.","live.title":"Jede Lektion live verfolgen","live.description":"Mach aus deiner Lektion ein lesbares Live-Transkript mit Übersetzung und optionalem Audio.","assist.title":"Schwierige Inhalte verstehen","assist.description":"Bei einem schwierigen Konzept kannst du eine Erklärung, eine direkte Antwort oder eine kurze Zusammenfassung anfordern.","notes.title":"Gute Notizen behalten","notes.description":"Halte Wichtiges mit Smart Notes fest und speichere die ganze Sitzung zum späteren Lernen.","dashboard.title":"Lektionen prüfen und verwalten","dashboard.description":"Alles Gespeicherte liegt im lokalen Dashboard — suchen, prüfen, Lernstruktur verfolgen und exportieren.","how.eyebrow":"So funktioniert es","how.title":"Von der Live-Lektion zu gespeicherten Lernnotizen.","how.lead":"Zwei einfache Wege — einer zum Folgen, einer zum Verstehen.","learning.eyebrow":"Von der Lektion zum Lernen","learning.title":"Mach aus Unterrichtskontext einen Lernweg.","learning.lead":"Ein Transkript zeigt, was gesagt wurde. Zova kann gespeicherte Unterrichtsinhalte in eine fokussierte Lernstruktur ordnen.","learning.savedTitle":"Gespeicherte Klasse","learning.savedDescription":"Transkript, Übersetzung, Smart Notes und relevante Lerninhalte gemeinsam lokal speichern.","learning.graphTitle":"Learning Graph","learning.graphDescription":"Ordne die Lektion in Kapitel, Themen und Konzepte — nicht in einzelne Sätze.","learning.detailTitle":"Study Detail","learning.detailDescription":"Öffne eine geführte Lerneinheit für ein Konzept im Kontext der Lektion.","learning.reviewTitle":"Schrittweise wiederholen","learning.reviewDescription":"Beginne mit Kernidee und Schlüsselpunkten und vertiefe dich bei Bedarf in Beispiele, typische Fehler, Quick Check und Details."},
    zh:{"features.eyebrow":"功能","features.title":"跟上每一堂课所需的一切。","features.lead":"Zova 在课程旁边工作，提供转录、翻译和学习帮助，无需离开当前页面。","live.title":"实时跟上课程","live.description":"将正在观看的课程变成可阅读的实时转录，并提供翻译和可选语音。","assist.title":"理解困难内容","assist.description":"遇到概念困难时，可根据近期课程上下文请求解释、直接回答或简短总结。","notes.title":"保存重要笔记","notes.description":"用 Smart Notes 记录重点，并保存完整课程以便以后学习。","dashboard.title":"复习和管理课程","dashboard.description":"所有保存内容都在本地 Dashboard 中，可搜索、复习、查看学习结构并导出。","how.eyebrow":"使用方法","how.title":"从实时课程到保存的学习笔记。","how.lead":"两条简单路径：跟上课程，或深入理解。","learning.eyebrow":"从课程到学习","learning.title":"把课堂上下文变成可跟随的学习路径。","learning.lead":"转录记录说了什么，Zova 可以把保存的课堂证据整理成聚焦的学习结构，帮助你循序复习。","learning.savedTitle":"保存的课程","learning.savedDescription":"在本地课程历史中保存转录、翻译、Smart Notes 和相关学习内容。","learning.graphTitle":"Learning Graph","learning.graphDescription":"将课程组织为章节、主题和概念，而不是每句话一个节点。","learning.detailTitle":"Study Detail","learning.detailDescription":"为选定概念打开带有课程上下文的引导式学习单元。","learning.reviewTitle":"渐进式复习","learning.reviewDescription":"先掌握核心思想和重点，再按需查看示例、常见错误、Quick Check 和深入内容。"},
    hi:{"features.eyebrow":"सुविधाएँ","features.title":"हर पाठ को समझने के लिए ज़रूरी सभी टूल।","features.lead":"Zova पेज छोड़े बिना ट्रांसक्रिप्शन, अनुवाद और पढ़ाई में मदद करता है।","live.title":"हर पाठ को लाइव समझें","live.description":"ऑनलाइन पाठ को अनुवाद और वैकल्पिक ऑडियो के साथ पढ़ने योग्य लाइव ट्रांसक्रिप्ट में बदलें।","assist.title":"कठिन विषय समझें","assist.description":"किसी अवधारणा पर अटकने पर हाल के कक्षा संदर्भ से स्पष्टीकरण, उत्तर या सारांश माँगें।","notes.title":"अच्छे नोट्स रखें","notes.description":"Smart Notes से ज़रूरी बातें लिखें और पूरी कक्षा को बाद में पढ़ने के लिए सेव करें।","dashboard.title":"पाठों की समीक्षा और प्रबंधन","dashboard.description":"सहेजी गई सामग्री स्थानीय Dashboard में खोजें, पढ़ें, सीखने की संरचना देखें और निर्यात करें।","how.eyebrow":"कैसे काम करता है","how.title":"लाइव पाठ से सेव किए गए अध्ययन नोट्स तक।","how.lead":"दो आसान रास्ते — पाठ को समझने और उसके कठिन हिस्सों को सीखने के लिए।","learning.eyebrow":"कक्षा से सीखने तक","learning.title":"कक्षा संदर्भ को सीखने के मार्ग में बदलें।","learning.lead":"ट्रांसक्रिप्ट बताता है कि क्या कहा गया। Zova कक्षा की सामग्री को केंद्रित सीखने की संरचना में व्यवस्थित कर सकता है।","learning.savedTitle":"सेव की गई कक्षा","learning.savedDescription":"ट्रांसक्रिप्ट, अनुवाद, Smart Notes और उपयोगी अध्ययन सामग्री को स्थानीय इतिहास में रखें।","learning.graphTitle":"Learning Graph","learning.graphDescription":"पाठ को अध्याय, विषय और अवधारणाओं में व्यवस्थित करें — हर वाक्य का अलग नोड नहीं।","learning.detailTitle":"Study Detail","learning.detailDescription":"चुनी हुई अवधारणा के लिए कक्षा संदर्भ सहित निर्देशित अध्ययन इकाई खोलें।","learning.reviewTitle":"क्रमिक समीक्षा","learning.reviewDescription":"पहले मुख्य विचार और बिंदु समझें, फिर उदाहरण, सामान्य गलतियाँ, Quick Check और गहराई में जाएँ।"}
  };
  var featureCopy = {
    en:{"smart.title":"Smart Class","smart.description":"Live classroom transcript with original and translated lesson text inside a focused, movable interface.","transcript.title":"Live Transcription","transcript.description":"Classroom tab audio is processed through Gemini Live to produce real-time transcript content.","translation.title":"Live Translation","translation.description":"Read lesson content in your selected language, right under the original.","dubbing.title":"Optional Dubbing","dubbing.description":"Translated audio playback, enabled separately from Smart Class and class saving.","explain.title":"Explain","explain.description":"Open a focused Google AI Mode explanation using recent classroom context.","answer.title":"Answer","answer.description":"Send bounded recent classroom context for a concise lesson answer.","summary.title":"Summary","summary.description":"Create a focused summary from recent classroom material."},
    de:{"smart.title":"Smart Class","smart.description":"Live-Transkript mit Original und Übersetzung in einer fokussierten, verschiebbaren Ansicht.","transcript.title":"Live-Transkription","transcript.description":"Audio aus dem Unterricht wird über Gemini Live zu einem Echtzeit-Transkript verarbeitet.","translation.title":"Live-Übersetzung","translation.description":"Lies den Unterricht direkt unter dem Original in deiner ausgewählten Sprache.","dubbing.title":"Optionales Dubbing","dubbing.description":"Übersetzte Audiowiedergabe, getrennt von Smart Class und dem Speichern aktivierbar.","explain.title":"Erklären","explain.description":"Öffne mit aktuellem Unterrichtskontext eine gezielte Erklärung in Google AI Mode.","answer.title":"Antwort","answer.description":"Sende begrenzten aktuellen Unterrichtskontext für eine kurze Antwort.","summary.title":"Zusammenfassung","summary.description":"Erstelle eine fokussierte Zusammenfassung des aktuellen Unterrichtsmaterials."},
    zh:{"smart.title":"Smart Class","smart.description":"在专注且可移动的界面中查看带原文和译文的实时课堂转录。","transcript.title":"实时转录","transcript.description":"通过 Gemini Live 处理课堂标签页音频，生成实时转录内容。","translation.title":"实时翻译","translation.description":"在原文下方用你选择的语言阅读课程内容。","dubbing.title":"可选配音","dubbing.description":"可单独开启翻译音频播放，不影响 Smart Class 和课程保存。","explain.title":"解释","explain.description":"根据近期课堂上下文打开聚焦的 Google AI Mode 解释。","answer.title":"回答","answer.description":"发送有限的近期课堂上下文，获得简洁的课程回答。","summary.title":"总结","summary.description":"根据近期课堂材料创建聚焦的总结。"},
    hi:{"smart.title":"Smart Class","smart.description":"केंद्रित और स्थानांतरित की जा सकने वाली विंडो में मूल और अनुवादित पाठ के साथ लाइव ट्रांसक्रिप्ट।","transcript.title":"लाइव ट्रांसक्रिप्शन","transcript.description":"कक्षा टैब के ऑडियो को Gemini Live से प्रोसेस करके रियल-टाइम ट्रांसक्रिप्ट बनाया जाता है।","translation.title":"लाइव अनुवाद","translation.description":"मूल पाठ के ठीक नीचे अपनी चुनी हुई भाषा में पाठ पढ़ें।","dubbing.title":"वैकल्पिक डबिंग","dubbing.description":"अनुवादित ऑडियो अलग से चालू करें; इससे Smart Class या सेविंग नहीं रुकती।","explain.title":"समझाएँ","explain.description":"हाल के कक्षा संदर्भ से Google AI Mode में केंद्रित स्पष्टीकरण खोलें।","answer.title":"उत्तर","answer.description":"संक्षिप्त उत्तर के लिए हाल का सीमित कक्षा संदर्भ भेजें।","summary.title":"सारांश","summary.description":"हाल की कक्षा सामग्री से केंद्रित सारांश बनाएँ।"}
  };
  Object.keys(featureCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},featureCopy[lang]);});
  var tourCopy = {
    en:{"tour.eyebrow":"See Zova in action","tour.title":"A guided tour of your study space.","tour.lead":"Follow the same flow every learner uses — from starting Zova to reviewing a saved class.","tour.startTitle":"Start Zova","tour.startDescription":"Choose your target language and start the classroom session.","tour.smartTitle":"Follow Smart Class","tour.smartDescription":"See original classroom content and the selected translation together as the lesson unfolds.","tour.helpTitle":"Ask for help","tour.helpDescription":"Use Explain, Answer or Summary when you need additional help understanding the lesson.","tour.saveTitle":"Save your class","tour.saveDescription":"Keep transcripts, translations and Smart Notes for later study — saved locally on your device.","tour.reviewTitle":"Review later","tour.reviewDescription":"Search, review, rename, export or delete saved lessons whenever you need them."},
    de:{"tour.eyebrow":"Zova in Aktion","tour.title":"Ein geführter Rundgang durch deinen Lernbereich.","tour.lead":"Folge dem Lernablauf — vom Start von Zova bis zur Wiederholung einer gespeicherten Klasse.","tour.startTitle":"Zova starten","tour.startDescription":"Wähle deine Zielsprache und starte die Unterrichtssitzung.","tour.smartTitle":"Smart Class folgen","tour.smartDescription":"Sieh Original und ausgewählte Übersetzung gemeinsam, während die Lektion weiterläuft.","tour.helpTitle":"Hilfe anfordern","tour.helpDescription":"Nutze Erklären, Antwort oder Zusammenfassung, wenn du zusätzliche Hilfe brauchst.","tour.saveTitle":"Klasse speichern","tour.saveDescription":"Speichere Transkripte, Übersetzungen und Smart Notes lokal zum späteren Lernen.","tour.reviewTitle":"Später wiederholen","tour.reviewDescription":"Gespeicherte Lektionen suchen, prüfen, umbenennen, exportieren oder löschen."},
    zh:{"tour.eyebrow":"查看 Zova 的实际使用","tour.title":"学习空间导览。","tour.lead":"按照学习流程操作：从启动 Zova 到复习保存的课程。","tour.startTitle":"启动 Zova","tour.startDescription":"选择目标语言并开始课堂会话。","tour.smartTitle":"跟随 Smart Class","tour.smartDescription":"课程进行时，同时查看课堂原文和所选译文。","tour.helpTitle":"寻求帮助","tour.helpDescription":"需要进一步理解课程时，使用解释、回答或总结。","tour.saveTitle":"保存课程","tour.saveDescription":"将转录、翻译和 Smart Notes 保存在本地，方便之后学习。","tour.reviewTitle":"稍后复习","tour.reviewDescription":"按需搜索、复习、重命名、导出或删除保存的课程。"},
    hi:{"tour.eyebrow":"Zova को काम करते देखें","tour.title":"आपके अध्ययन स्थान का मार्गदर्शित परिचय।","tour.lead":"Zova शुरू करने से लेकर सेव की गई कक्षा की समीक्षा तक पूरा सीखने का प्रवाह देखें।","tour.startTitle":"Zova शुरू करें","tour.startDescription":"लक्ष्य भाषा चुनें और कक्षा सत्र शुरू करें।","tour.smartTitle":"Smart Class के साथ सीखें","tour.smartDescription":"पाठ के दौरान मूल कक्षा सामग्री और चुना हुआ अनुवाद साथ-साथ देखें।","tour.helpTitle":"मदद माँगें","tour.helpDescription":"अधिक समझ के लिए Explain, Answer या Summary का उपयोग करें।","tour.saveTitle":"कक्षा सेव करें","tour.saveDescription":"ट्रांसक्रिप्ट, अनुवाद और Smart Notes को बाद में पढ़ने के लिए स्थानीय रूप से रखें।","tour.reviewTitle":"बाद में समीक्षा करें","tour.reviewDescription":"जब चाहें सेव किए गए पाठ खोजें, देखें, नाम बदलें, निर्यात करें या हटाएँ।"}
  };
  Object.keys(tourCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},tourCopy[lang]);});
  var pageHeadings = {
    en:{"guide.visualTitle":"From class to saved study notes","guide.installTitle":"Install Zova","guide.apiTitle":"Add your Gemini API key","guide.accessTitle":"Allow website access","guide.startTitle":"Start your class","guide.smartTitle":"Follow Smart Class","guide.helpTitle":"Ask for help","guide.dubbingTitle":"Optional translated audio","guide.saveTitle":"Save your class","guide.autosaveTitle":"Auto-Save protection","guide.reviewTitle":"Review later","guide.backupTitle":"Backup your classes","support.installTitle":"Installation","support.apiTitle":"Gemini API Key","support.accessTitle":"Website Access","support.startTitle":"Starting Zova","support.smartTitle":"Smart Class","support.translationTitle":"Translation","support.dubbingTitle":"Dubbing","support.helpTitle":"Explain / Answer / Summary","support.saveTitle":"Save Class","support.dashboardTitle":"Dashboard","support.backupTitle":"Backup / Restore","support.troubleshootTitle":"Zova doesn't start?","support.contactTitle":"Still stuck?"},
    de:{"guide.visualTitle":"Von der Klasse zu gespeicherten Lernnotizen","guide.installTitle":"Zova installieren","guide.apiTitle":"Gemini-API-Schlüssel hinzufügen","guide.accessTitle":"Website-Zugriff erlauben","guide.startTitle":"Klasse starten","guide.smartTitle":"Smart Class folgen","guide.helpTitle":"Hilfe anfordern","guide.dubbingTitle":"Optionale übersetzte Audiospur","guide.saveTitle":"Klasse speichern","guide.autosaveTitle":"Auto-Save-Schutz","guide.reviewTitle":"Später wiederholen","guide.backupTitle":"Klassen sichern","support.installTitle":"Installation","support.apiTitle":"Gemini-API-Schlüssel","support.accessTitle":"Website-Zugriff","support.startTitle":"Zova starten","support.smartTitle":"Smart Class","support.translationTitle":"Übersetzung","support.dubbingTitle":"Dubbing","support.helpTitle":"Erklären / Antworten / Zusammenfassen","support.saveTitle":"Klasse speichern","support.dashboardTitle":"Dashboard","support.backupTitle":"Sichern / Wiederherstellen","support.troubleshootTitle":"Zova startet nicht?","support.contactTitle":"Noch Probleme?"},
    zh:{"guide.visualTitle":"从课程到保存的学习笔记","guide.installTitle":"安装 Zova","guide.apiTitle":"添加 Gemini API 密钥","guide.accessTitle":"允许网站访问","guide.startTitle":"开始课程","guide.smartTitle":"跟随 Smart Class","guide.helpTitle":"寻求帮助","guide.dubbingTitle":"可选翻译音频","guide.saveTitle":"保存课程","guide.autosaveTitle":"自动保存保护","guide.reviewTitle":"稍后复习","guide.backupTitle":"备份课程","support.installTitle":"安装","support.apiTitle":"Gemini API 密钥","support.accessTitle":"网站访问","support.startTitle":"启动 Zova","support.smartTitle":"Smart Class","support.translationTitle":"翻译","support.dubbingTitle":"配音","support.helpTitle":"解释 / 回答 / 总结","support.saveTitle":"保存课程","support.dashboardTitle":"Dashboard","support.backupTitle":"备份 / 恢复","support.troubleshootTitle":"Zova 无法启动？","support.contactTitle":"仍然遇到问题？"},
    hi:{"guide.visualTitle":"कक्षा से सेव किए गए अध्ययन नोट्स तक","guide.installTitle":"Zova इंस्टॉल करें","guide.apiTitle":"Gemini API कुंजी जोड़ें","guide.accessTitle":"वेबसाइट एक्सेस की अनुमति दें","guide.startTitle":"कक्षा शुरू करें","guide.smartTitle":"Smart Class को फॉलो करें","guide.helpTitle":"मदद माँगें","guide.dubbingTitle":"वैकल्पिक अनुवादित ऑडियो","guide.saveTitle":"कक्षा सेव करें","guide.autosaveTitle":"ऑटो-सेव सुरक्षा","guide.reviewTitle":"बाद में समीक्षा करें","guide.backupTitle":"कक्षाओं का बैकअप लें","support.installTitle":"इंस्टॉलेशन","support.apiTitle":"Gemini API कुंजी","support.accessTitle":"वेबसाइट एक्सेस","support.startTitle":"Zova शुरू करना","support.smartTitle":"Smart Class","support.translationTitle":"अनुवाद","support.dubbingTitle":"डबिंग","support.helpTitle":"समझाएँ / उत्तर / सारांश","support.saveTitle":"कक्षा सेव करें","support.dashboardTitle":"Dashboard","support.backupTitle":"बैकअप / पुनर्स्थापना","support.troubleshootTitle":"Zova शुरू नहीं होता?","support.contactTitle":"अब भी समस्या है?"}
  };
  copy.headingCopy=pageHeadings;
  copy.pages = {
    en:{"guide.eyebrow":"User guide","guide.title":"How to use Zova","guide.subtitle":"From installation to your first saved class.","guide.learnEyebrow":"Learn with Zova","guide.learnTitle":"Live translation in 78 world languages.","guide.learnDescription":"Zova detects the lesson language automatically, then helps you follow the class with live transcription, translation, optional translated audio and study notes.","guide.free":"100% free to use","support.eyebrow":"We're here to help","support.title":"Zova Support"},
    de:{"guide.eyebrow":"Anleitung","guide.title":"So verwendest du Zova","guide.subtitle":"Von der Installation bis zur ersten gespeicherten Klasse.","guide.learnEyebrow":"Mit Zova lernen","guide.learnTitle":"Live-Übersetzung in 78 Sprachen.","guide.learnDescription":"Zova erkennt die Unterrichtssprache automatisch und hilft dir mit Live-Transkription, Übersetzung, optionalem Audio und Lernnotizen.","guide.free":"100 % kostenlos","support.eyebrow":"Wir helfen dir","support.title":"Zova Support"},
    zh:{"guide.eyebrow":"使用指南","guide.title":"如何使用 Zova","guide.subtitle":"从安装到保存第一堂课。","guide.learnEyebrow":"使用 Zova 学习","guide.learnTitle":"支持 78 种语言的实时翻译。","guide.learnDescription":"Zova 自动识别课程语言，并通过实时转录、翻译、可选语音和学习笔记帮助你跟上课程。","guide.free":"完全免费使用","support.eyebrow":"我们随时提供帮助","support.title":"Zova 支持"},
    hi:{"guide.eyebrow":"उपयोग गाइड","guide.title":"Zova का उपयोग कैसे करें","guide.subtitle":"इंस्टॉल करने से पहली सेव की गई कक्षा तक।","guide.learnEyebrow":"Zova के साथ सीखें","guide.learnTitle":"78 भाषाओं में लाइव अनुवाद।","guide.learnDescription":"Zova कक्षा की भाषा अपने आप पहचानता है और लाइव ट्रांसक्रिप्शन, अनुवाद, वैकल्पिक ऑडियो और अध्ययन नोट्स से सीखने में मदद करता है।","guide.free":"100% मुफ़्त","support.eyebrow":"हम मदद के लिए यहाँ हैं","support.title":"Zova सहायता"}
  };
  Object.keys(copy.headingCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},copy.headingCopy[lang]);});
  var faqCopy = {
    en:{"faq.title":"Frequently asked questions","faq.whatIs.title":"What is Zova?","faq.whatIs.answer":"Zova is an AI-powered Chrome extension that helps you follow online lessons with live transcription, translation, optional translated audio, classroom explanations, summaries and locally saved study notes.","faq.storage.title":"Where are my classes stored?","faq.storage.answer":"Saved classes are stored locally in Chrome extension storage on your device — not on a Zova server.","faq.dubbing.title":"Can I turn Dubbing off?","faq.dubbing.answer":"Yes. Translated audio is optional and can be enabled or disabled separately from Smart Class and class saving.","faq.explain.title":"What happens when I click Explain?","faq.explain.answer":"Zova opens Google AI Mode in a compact popup and submits bounded recent classroom context for a clearer explanation of the lesson.","faq.answer.title":"What happens when I click Answer?","faq.answer.answer":"Zova submits bounded recent classroom context to Google AI Mode for a concise, direct answer to your lesson question.","faq.summary.title":"What happens when I click Summary?","faq.summary.answer":"Zova opens Google AI Mode with bounded recent context and creates a focused summary of recent classroom material."},
    de:{"faq.title":"Häufig gestellte Fragen","faq.whatIs.title":"Was ist Zova?","faq.whatIs.answer":"Zova ist eine Chrome-Erweiterung mit KI, die dich mit Live-Transkription, Übersetzung, optionalem Audio, Unterrichtserklärungen, Zusammenfassungen und lokal gespeicherten Notizen durch Online-Lektionen begleitet.","faq.storage.title":"Wo werden meine Klassen gespeichert?","faq.storage.answer":"Gespeicherte Klassen liegen lokal im Chrome-Erweiterungsspeicher auf deinem Gerät — nicht auf einem Zova-Server.","faq.dubbing.title":"Kann ich Dubbing ausschalten?","faq.dubbing.answer":"Ja. Übersetztes Audio ist optional und kann unabhängig von Smart Class und dem Speichern aktiviert oder deaktiviert werden.","faq.explain.title":"Was passiert bei Klick auf Erklären?","faq.explain.answer":"Zova öffnet Google AI Mode in einem kompakten Fenster und sendet begrenzten aktuellen Unterrichtskontext für eine klarere Erklärung.","faq.answer.title":"Was passiert bei Klick auf Antwort?","faq.answer.answer":"Zova sendet begrenzten aktuellen Unterrichtskontext an Google AI Mode für eine kurze, direkte Antwort auf deine Frage.","faq.summary.title":"Was passiert bei Klick auf Zusammenfassung?","faq.summary.answer":"Zova öffnet Google AI Mode mit begrenztem aktuellem Kontext und erstellt eine fokussierte Zusammenfassung."},
    zh:{"faq.title":"常见问题","faq.whatIs.title":"什么是 Zova？","faq.whatIs.answer":"Zova 是一款 AI Chrome 扩展，可通过实时转录、翻译、可选译音、课堂解释、总结和本地学习笔记帮助你跟上在线课程。","faq.storage.title":"我的课程保存在哪里？","faq.storage.answer":"保存的课程存储在设备上的 Chrome 扩展本地存储中，而不是 Zova 服务器上。","faq.dubbing.title":"可以关闭配音吗？","faq.dubbing.answer":"可以。翻译音频是可选的，可以独立于 Smart Class 和课程保存功能开启或关闭。","faq.explain.title":"点击解释会发生什么？","faq.explain.answer":"Zova 会在紧凑窗口中打开 Google AI Mode，并发送有限的近期课堂上下文以获得更清晰的解释。","faq.answer.title":"点击回答会发生什么？","faq.answer.answer":"Zova 会向 Google AI Mode 发送有限的近期课堂上下文，为你的课程问题提供简洁直接的回答。","faq.summary.title":"点击总结会发生什么？","faq.summary.answer":"Zova 会使用有限的近期上下文打开 Google AI Mode，并创建聚焦的课程总结。"},
    hi:{"faq.title":"अक्सर पूछे जाने वाले सवाल","faq.whatIs.title":"Zova क्या है?","faq.whatIs.answer":"Zova एक AI Chrome एक्सटेंशन है जो लाइव ट्रांसक्रिप्शन, अनुवाद, वैकल्पिक ऑडियो, कक्षा स्पष्टीकरण, सारांश और स्थानीय नोट्स से ऑनलाइन पाठ समझने में मदद करता है।","faq.storage.title":"मेरी कक्षाएँ कहाँ सेव होती हैं?","faq.storage.answer":"सेव की गई कक्षाएँ आपके डिवाइस के Chrome एक्सटेंशन स्टोरेज में स्थानीय रूप से रहती हैं — Zova सर्वर पर नहीं।","faq.dubbing.title":"क्या Dubbing बंद कर सकते हैं?","faq.dubbing.answer":"हाँ। अनुवादित ऑडियो वैकल्पिक है और Smart Class तथा सेविंग से अलग चालू या बंद किया जा सकता है।","faq.explain.title":"Explain पर क्लिक करने से क्या होता है?","faq.explain.answer":"Zova एक छोटे पॉपअप में Google AI Mode खोलता है और स्पष्ट व्याख्या के लिए सीमित हाल का कक्षा संदर्भ भेजता है।","faq.answer.title":"Answer पर क्लिक करने से क्या होता है?","faq.answer.answer":"Zova आपके पाठ के प्रश्न का संक्षिप्त और सीधा उत्तर पाने के लिए सीमित हाल का कक्षा संदर्भ Google AI Mode को भेजता है।","faq.summary.title":"Summary पर क्लिक करने से क्या होता है?","faq.summary.answer":"Zova सीमित हाल के संदर्भ के साथ Google AI Mode खोलता है और केंद्रित सारांश बनाता है।"}
  };
  Object.keys(faqCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},faqCopy[lang]);});
  var finalCopy = {
    en:{"faq.eyebrow":"Questions","faq.api.title":"Do I need a Gemini API key?","faq.api.answer":"Yes. Zova uses a user-provided Gemini API key for Gemini-powered live processing. You create the key in Google AI Studio and paste it into Zova Settings.","faq.mic.title":"Does Zova record my microphone?","faq.mic.answer":"No. Normal Smart Class uses selected-tab audio via tab capture, not your physical microphone. Microphone permission may appear only for compatibility or verification purposes.","faq.rawAudio.title":"Does Zova save raw classroom audio?","faq.rawAudio.answer":"No. Raw classroom audio is not intentionally persisted by Zova. It is processed for the live features you request.","faq.save.title":"Does Save Class work without Dubbing?","faq.save.answer":"Yes. Turning Dubbing off does not prevent Smart Class, the transcript, Save Class or Auto-Save.","cta.eyebrow":"Ready when you are","cta.title":"Make every lesson easier to follow.","cta.lead":"Zova is coming to the Chrome Web Store soon."},
    de:{"faq.eyebrow":"Fragen","faq.api.title":"Brauche ich einen Gemini-API-Schlüssel?","faq.api.answer":"Ja. Zova verwendet einen von dir bereitgestellten Gemini-API-Schlüssel für die Live-Verarbeitung. Er wird in Google AI Studio erstellt und in den Zova-Einstellungen eingefügt.","faq.mic.title":"Nimmt Zova mein Mikrofon auf?","faq.mic.answer":"Nein. Smart Class verwendet normalerweise Audio des ausgewählten Tabs über Tab Capture, nicht dein physisches Mikrofon.","faq.rawAudio.title":"Speichert Zova rohes Unterrichtsaudio?","faq.rawAudio.answer":"Nein. Rohes Unterrichtsaudio wird von Zova nicht absichtlich gespeichert und nur für angeforderte Live-Funktionen verarbeitet.","faq.save.title":"Funktioniert Save Class ohne Dubbing?","faq.save.answer":"Ja. Das Ausschalten von Dubbing verhindert Smart Class, Transkript, Save Class oder Auto-Save nicht.","cta.eyebrow":"Bereit, wenn du es bist","cta.title":"Mach jede Lektion leichter verständlich.","cta.lead":"Zova kommt bald in den Chrome Web Store."},
    zh:{"faq.eyebrow":"问题","faq.api.title":"需要 Gemini API 密钥吗？","faq.api.answer":"需要。Zova 使用用户提供的 Gemini API 密钥进行 Gemini 实时处理。你可以在 Google AI Studio 创建密钥并粘贴到 Zova 设置中。","faq.mic.title":"Zova 会录制我的麦克风吗？","faq.mic.answer":"不会。Smart Class 通常通过标签页捕获使用所选标签页的音频，而不是物理麦克风。","faq.rawAudio.title":"Zova 会保存原始课堂音频吗？","faq.rawAudio.answer":"不会。Zova 不会有意保存原始课堂音频，只会为你请求的实时功能进行处理。","faq.save.title":"没有配音时可以保存课程吗？","faq.save.answer":"可以。关闭配音不会阻止 Smart Class、转录、保存课程或自动保存。","cta.eyebrow":"随时开始","cta.title":"让每堂课都更容易跟上。","cta.lead":"Zova 即将登陆 Chrome Web Store。"},
    hi:{"faq.eyebrow":"सवाल","faq.api.title":"क्या Gemini API कुंजी चाहिए?","faq.api.answer":"हाँ। Zova लाइव प्रोसेसिंग के लिए उपयोगकर्ता की दी हुई Gemini API कुंजी इस्तेमाल करता है। इसे Google AI Studio में बनाकर Zova Settings में डालें।","faq.mic.title":"क्या Zova मेरा माइक्रोफ़ोन रिकॉर्ड करता है?","faq.mic.answer":"नहीं। Smart Class सामान्य रूप से भौतिक माइक्रोफ़ोन के बजाय चुने हुए टैब का ऑडियो इस्तेमाल करता है।","faq.rawAudio.title":"क्या Zova कक्षा का कच्चा ऑडियो सेव करता है?","faq.rawAudio.answer":"नहीं। कच्चा कक्षा ऑडियो जानबूझकर सेव नहीं किया जाता; इसे केवल अनुरोधित लाइव सुविधाओं के लिए प्रोसेस किया जाता है।","faq.save.title":"क्या Dubbing के बिना Save Class काम करता है?","faq.save.answer":"हाँ। Dubbing बंद करने से Smart Class, ट्रांसक्रिप्ट, Save Class या Auto-Save बंद नहीं होते।","cta.eyebrow":"जब आप तैयार हों","cta.title":"हर पाठ को समझना आसान बनाएँ।","cta.lead":"Zova जल्द ही Chrome Web Store पर आएगा।"}
  };
  Object.keys(finalCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},finalCopy[lang]);});
  var pageIntroCopy = {
    en:{"guide.googleTitle":"Start with Google AI Studio","guide.googleDescription":"Before your first live session, create your own Gemini API key in Google AI Studio. It is stored locally in Zova.","guide.googleButton":"Open Google AI Studio →","guide.googleNote":"Zova is 100% free. Google API limits or terms may apply separately.","support.intro":"Need a hand with Zova? Browse the topics below or email"},
    de:{"guide.googleTitle":"Mit Google AI Studio starten","guide.googleDescription":"Erstelle vor deiner ersten Live-Sitzung deinen eigenen Gemini-API-Schlüssel in Google AI Studio. Er wird lokal in Zova gespeichert.","guide.googleButton":"Google AI Studio öffnen →","guide.googleNote":"Zova ist 100 % kostenlos. Für die Google-API können eigene Limits oder Bedingungen gelten.","support.intro":"Brauchst du Hilfe mit Zova? Durchsuche die Themen unten oder schreibe an"},
    zh:{"guide.googleTitle":"从 Google AI Studio 开始","guide.googleDescription":"在第一次实时课程前，在 Google AI Studio 创建自己的 Gemini API 密钥。密钥会保存在 Zova 本地。","guide.googleButton":"打开 Google AI Studio →","guide.googleNote":"Zova 完全免费。Google API 可能有单独的限制或条款。","support.intro":"需要 Zova 帮助吗？浏览下面的主题或发送邮件至"},
    hi:{"guide.googleTitle":"Google AI Studio से शुरू करें","guide.googleDescription":"पहले लाइव सत्र से पहले Google AI Studio में अपनी Gemini API कुंजी बनाएँ। यह Zova में स्थानीय रूप से रखी जाती है।","guide.googleButton":"Google AI Studio खोलें →","guide.googleNote":"Zova 100% मुफ़्त है। Google API की अपनी सीमाएँ या शर्तें हो सकती हैं।","support.intro":"Zova में मदद चाहिए? नीचे दिए विषय देखें या ईमेल करें"}
  };
  Object.keys(pageIntroCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},pageIntroCopy[lang]);});
  var guideDetailCopy = {
    en:{"guide.visualDescription":"Use this visual path to understand how Zova detects, translates and saves your lesson.","guide.installDescription":"Zova will be available from the Chrome Web Store soon. For now, you can install it as a developer or tester using the unpacked extension flow.","guide.apiDescription":"Before starting a lesson, connect Zova to Google Gemini with your own API key. Zova is 100% free to use; Google API limits or terms may apply separately.","guide.accessDescription":"When you start Zova on a classroom or video website, Chrome may ask you to allow access to that site.","guide.accessInstruction":"Click Allow only for the lesson page you selected. This lets Smart Class appear beside the classroom and work with the active session.","guide.smartDescription":"See original classroom content and the selected translation together as the lesson unfolds.","guide.helpDescription":"Use Explain, Answer or Summary when you need additional help understanding the lesson.","guide.helpInstruction":"These actions open Google AI Mode in a compact popup and submit bounded recent classroom context.","guide.dubbingDescription":"Dubbing (translated audio playback) is optional. You can enable or disable it separately from the rest of Zova.","guide.saveDescription":"Keep transcripts, translations and Smart Notes for later study — saved locally on your device.","guide.autosaveDescription":"While Smart Class is active, meaningful changes can be automatically saved — so you don't have to constantly press Save.","guide.reviewDescription":"Search, review, rename, export or delete saved lessons whenever you need them."},
    de:{"guide.visualDescription":"Nutze diesen visuellen Ablauf, um zu verstehen, wie Zova deine Lektion erkennt, übersetzt und speichert.","guide.installDescription":"Zova wird bald im Chrome Web Store verfügbar sein. Bis dahin kannst du die Erweiterung als Entwickler oder Tester entpackt installieren.","guide.apiDescription":"Verbinde Zova vor der ersten Lektion mit deinem eigenen Google-Gemini-API-Schlüssel. Zova ist kostenlos; Google-API-Limits oder Bedingungen können separat gelten.","guide.accessDescription":"Wenn du Zova auf einer Unterrichts- oder Videoseite startest, kann Chrome nach dem Zugriff auf diese Seite fragen.","guide.accessInstruction":"Klicke nur für die ausgewählte Lektion auf Erlauben. Dadurch kann Smart Class neben dem Unterricht erscheinen und mit der aktiven Sitzung arbeiten.","guide.smartDescription":"Sieh Original und ausgewählte Übersetzung gemeinsam, während die Lektion weiterläuft.","guide.helpDescription":"Nutze Erklären, Antwort oder Zusammenfassung, wenn du zusätzliche Hilfe beim Verstehen brauchst.","guide.helpInstruction":"Diese Aktionen öffnen Google AI Mode in einem kompakten Fenster und senden begrenzten aktuellen Unterrichtskontext.","guide.dubbingDescription":"Dubbing (übersetzte Audiowiedergabe) ist optional und kann unabhängig vom restlichen Zova aktiviert oder deaktiviert werden.","guide.saveDescription":"Bewahre Transkripte, Übersetzungen und Smart Notes lokal zum späteren Lernen auf.","guide.autosaveDescription":"Während Smart Class aktiv ist, können wichtige Änderungen automatisch gespeichert werden.","guide.reviewDescription":"Gespeicherte Lektionen suchen, prüfen, umbenennen, exportieren oder löschen."},
    zh:{"guide.visualDescription":"通过这条视觉路径了解 Zova 如何识别、翻译并保存课程。","guide.installDescription":"Zova 即将登陆 Chrome Web Store。目前可以通过解压扩展流程以开发者或测试者身份安装。","guide.apiDescription":"开始课程前，使用自己的 Google Gemini API 密钥连接 Zova。Zova 完全免费，Google API 可能有单独限制或条款。","guide.accessDescription":"在课堂或视频网站启动 Zova 时，Chrome 可能会请求网站访问权限。","guide.accessInstruction":"只为你选择的课程页面点击允许，这样 Smart Class 才能显示在课堂旁边并处理当前会话。","guide.smartDescription":"课程进行时，同时查看课堂原文和所选译文。","guide.helpDescription":"需要进一步理解课程时，使用解释、回答或总结。","guide.helpInstruction":"这些操作会在紧凑窗口中打开 Google AI Mode，并提交有限的近期课堂上下文。","guide.dubbingDescription":"配音（翻译音频播放）是可选功能，可以独立于其他 Zova 功能开启或关闭。","guide.saveDescription":"将转录、翻译和 Smart Notes 保存在本地，方便之后学习。","guide.autosaveDescription":"Smart Class 运行时，重要变化可以自动保存，无需不断点击保存。","guide.reviewDescription":"按需搜索、复习、重命名、导出或删除保存的课程。"},
    hi:{"guide.visualDescription":"इस दृश्य मार्ग से समझें कि Zova आपके पाठ को कैसे पहचानता, अनुवाद करता और सेव करता है।","guide.installDescription":"Zova जल्द ही Chrome Web Store पर उपलब्ध होगा। अभी इसे developer या tester के रूप में unpacked extension से इंस्टॉल कर सकते हैं।","guide.apiDescription":"पाठ शुरू करने से पहले अपनी Google Gemini API कुंजी से Zova कनेक्ट करें। Zova मुफ़्त है; Google API की सीमाएँ या शर्तें अलग हो सकती हैं।","guide.accessDescription":"कक्षा या वीडियो वेबसाइट पर Zova शुरू करते समय Chrome उस साइट की अनुमति माँग सकता है।","guide.accessInstruction":"केवल चुने गए पाठ पेज के लिए Allow पर क्लिक करें। इससे Smart Class कक्षा के पास दिखाई देगा और सक्रिय सत्र के साथ काम करेगा।","guide.smartDescription":"पाठ के दौरान मूल कक्षा सामग्री और चुना हुआ अनुवाद साथ-साथ देखें।","guide.helpDescription":"पाठ समझने में अतिरिक्त मदद के लिए Explain, Answer या Summary का उपयोग करें।","guide.helpInstruction":"ये क्रियाएँ छोटे पॉपअप में Google AI Mode खोलती हैं और सीमित हाल का कक्षा संदर्भ भेजती हैं।","guide.dubbingDescription":"Dubbing (अनुवादित ऑडियो) वैकल्पिक है और Zova की बाकी सुविधाओं से अलग चालू या बंद किया जा सकता है।","guide.saveDescription":"ट्रांसक्रिप्ट, अनुवाद और Smart Notes को बाद में पढ़ने के लिए स्थानीय रूप से रखें।","guide.autosaveDescription":"Smart Class सक्रिय होने पर महत्वपूर्ण बदलाव अपने आप सेव हो सकते हैं।","guide.reviewDescription":"जब चाहें सेव किए गए पाठ खोजें, देखें, नाम बदलें, निर्यात करें या हटाएँ।"}
  };
  Object.keys(guideDetailCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},guideDetailCopy[lang]);});
  var supportDetailCopy = {
    en:{"support.installDescription":"Zova is coming to the Chrome Web Store soon. For now, install it as an unpacked extension.","support.apiDescription":"Zova needs your own Gemini API key for live processing.","support.accessDescription":"Chrome may ask you to allow access to a classroom or video site.","support.troubleshootDescription":"Try these checks in order.","support.contactDescription":"Email us and we'll help you get back to learning."},
    de:{"support.installDescription":"Zova kommt bald in den Chrome Web Store. Bis dahin kannst du die Erweiterung entpackt installieren.","support.apiDescription":"Zova benötigt deinen eigenen Gemini-API-Schlüssel für die Live-Verarbeitung.","support.accessDescription":"Chrome kann dich bitten, den Zugriff auf eine Unterrichts- oder Videoseite zu erlauben.","support.troubleshootDescription":"Probiere diese Prüfungen der Reihe nach aus.","support.contactDescription":"Schreib uns, und wir helfen dir beim Weiterlernen."},
    zh:{"support.installDescription":"Zova 即将登陆 Chrome Web Store。目前可以将其作为解压扩展安装。","support.apiDescription":"Zova 的实时处理需要你自己的 Gemini API 密钥。","support.accessDescription":"Chrome 可能会请求允许访问课堂或视频网站。","support.troubleshootDescription":"请按顺序尝试以下检查。","support.contactDescription":"给我们发邮件，我们会帮助你继续学习。"},
    hi:{"support.installDescription":"Zova जल्द ही Chrome Web Store पर आएगा। अभी इसे unpacked extension के रूप में इंस्टॉल करें।","support.apiDescription":"लाइव प्रोसेसिंग के लिए Zova को आपकी अपनी Gemini API कुंजी चाहिए।","support.accessDescription":"Chrome आपसे कक्षा या वीडियो साइट का एक्सेस देने को कह सकता है।","support.troubleshootDescription":"इन जाँचों को क्रम से आज़माएँ।","support.contactDescription":"हमें ईमेल करें और हम आपको सीखना जारी रखने में मदद करेंगे।"}
  };
  Object.keys(supportDetailCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},supportDetailCopy[lang]);});
  var captionCopy = {
    en:{"guide.visualCaption1":"1. Open a saved class and choose the study action you need.","guide.visualCaption2":"2. Keep Smart Notes and a Clean Study File together with the class.","guide.visualCaption3":"3. During the lesson, Zova detects the language and shows the translation beside the live transcript."},
    de:{"guide.visualCaption1":"1. Öffne eine gespeicherte Klasse und wähle die gewünschte Lernaktion.","guide.visualCaption2":"2. Bewahre Smart Notes und eine Clean Study File gemeinsam mit der Klasse auf.","guide.visualCaption3":"3. Während der Lektion erkennt Zova die Sprache und zeigt die Übersetzung neben dem Live-Transkript."},
    zh:{"guide.visualCaption1":"1. 打开保存的课程并选择需要的学习操作。","guide.visualCaption2":"2. 将 Smart Notes 和 Clean Study File 与课程一起保存。","guide.visualCaption3":"3. 课程进行时，Zova 会识别语言，并在实时转录旁显示翻译。"},
    hi:{"guide.visualCaption1":"1. सेव की गई कक्षा खोलें और आवश्यक अध्ययन क्रिया चुनें।","guide.visualCaption2":"2. Smart Notes और Clean Study File को कक्षा के साथ रखें।","guide.visualCaption3":"3. पाठ के दौरान Zova भाषा पहचानता है और लाइव ट्रांसक्रिप्ट के पास अनुवाद दिखाता है।"}
  };
  Object.keys(captionCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},captionCopy[lang]);});
  var accessCopy = {
    en:{"guide.accessClick":"Click","guide.accessOnly":"only for the lesson page you selected. This lets Smart Class appear beside the classroom and work with the active session."},
    de:{"guide.accessClick":"Klicke","guide.accessOnly":"nur für die ausgewählte Unterrichtsseite auf diese Erlaubnis. Dadurch kann Smart Class neben dem Unterricht erscheinen und mit der aktiven Sitzung arbeiten."},
    zh:{"guide.accessClick":"点击","guide.accessOnly":"仅为你选择的课程页面允许访问。这样 Smart Class 才能显示在课堂旁边并处理当前会话。"},
    hi:{"guide.accessClick":"क्लिक करें","guide.accessOnly":"केवल चुने गए पाठ पेज के लिए अनुमति दें। इससे Smart Class कक्षा के पास दिखाई देगा और सक्रिय सत्र के साथ काम करेगा।"}
  };
  Object.keys(accessCopy).forEach(function(lang){copy.pages[lang]=Object.assign(copy.pages[lang]||{},accessCopy[lang]);});
  var footerCopy = {
    en:{"footer.description":"AI-powered classroom assistance for Chrome. Understand every class, in your language.","footer.product":"Product","footer.resources":"Resources","footer.features":"Features","footer.how":"How it works","footer.screenshots":"Screenshots","footer.learn":"Learn","footer.privacy":"Privacy Policy","footer.privacyShort":"Privacy","footer.support":"Support","footer.home":"Home"},
    de:{"footer.description":"KI-Unterstützung für den Unterricht in Chrome. Verstehe jede Klasse in deiner Sprache.","footer.product":"Produkt","footer.resources":"Ressourcen","footer.features":"Funktionen","footer.how":"So funktioniert es","footer.screenshots":"Screenshots","footer.learn":"Anleitung","footer.privacy":"Datenschutz","footer.privacyShort":"Datenschutz","footer.support":"Support","footer.home":"Startseite"},
    zh:{"footer.description":"Chrome 智能课堂助手。用你的语言理解每一堂课。","footer.product":"产品","footer.resources":"资源","footer.features":"功能","footer.how":"使用方法","footer.screenshots":"截图","footer.learn":"指南","footer.privacy":"隐私政策","footer.privacyShort":"隐私","footer.support":"支持","footer.home":"首页"},
    hi:{"footer.description":"Chrome के लिए AI कक्षा सहायक। हर कक्षा को अपनी भाषा में समझें।","footer.product":"उत्पाद","footer.resources":"संसाधन","footer.features":"सुविधाएँ","footer.how":"कैसे काम करता है","footer.screenshots":"स्क्रीनशॉट","footer.learn":"गाइड","footer.privacy":"गोपनीयता नीति","footer.privacyShort":"गोपनीयता","footer.support":"सहायता","footer.home":"होम"}
  };
  Object.keys(footerCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},footerCopy[lang]);});
  var detailCopy = {
    en:{"notes.itemDescription":"Keep useful lesson notes together with the saved class.","save.itemDescription":"Save the current classroom session for later review.","autosave.itemDescription":"Automatically protect meaningful class changes while Smart Class is active.","dashboard.itemDescription":"Review saved classes, study time, transcripts, Smart Notes and structured learning material from one place.","search.itemDescription":"Search inside your saved classes to find a moment fast.","manage.itemDescription":"Manage your saved lesson history.","export.itemDescription":"Download lesson notes and content when you need them.","backup.itemDescription":"Export saved classes to a backup file and restore them later."},
    de:{"notes.itemDescription":"Bewahre nützliche Notizen gemeinsam mit der gespeicherten Klasse auf.","save.itemDescription":"Speichere die aktuelle Unterrichtssitzung zur späteren Wiederholung.","autosave.itemDescription":"Schütze wichtige Änderungen automatisch, während Smart Class aktiv ist.","dashboard.itemDescription":"Prüfe gespeicherte Klassen, Lernzeit, Transkripte, Smart Notes und strukturierte Lerninhalte an einem Ort.","search.itemDescription":"Durchsuche gespeicherte Klassen, um eine Stelle schnell zu finden.","manage.itemDescription":"Verwalte deinen gespeicherten Unterrichtsverlauf.","export.itemDescription":"Lade Lernnotizen und Inhalte bei Bedarf herunter.","backup.itemDescription":"Exportiere gespeicherte Klassen als Sicherung und stelle sie später wieder her."},
    zh:{"notes.itemDescription":"将有用的课堂笔记与保存的课程放在一起。","save.itemDescription":"保存当前课堂会话，方便之后复习。","autosave.itemDescription":"Smart Class 运行时自动保护重要的课程变化。","dashboard.itemDescription":"在一个地方查看保存的课程、学习时间、转录、Smart Notes 和结构化学习内容。","search.itemDescription":"在保存的课程中搜索，快速找到需要的片段。","manage.itemDescription":"管理保存的课程历史。","export.itemDescription":"按需下载学习笔记和课程内容。","backup.itemDescription":"将保存的课程导出为备份，之后再恢复。"},
    hi:{"notes.itemDescription":"उपयोगी कक्षा नोट्स को सेव की गई कक्षा के साथ रखें।","save.itemDescription":"वर्तमान कक्षा सत्र को बाद में समीक्षा के लिए सेव करें।","autosave.itemDescription":"Smart Class सक्रिय रहने पर महत्वपूर्ण बदलावों को अपने आप सुरक्षित करें।","dashboard.itemDescription":"एक ही जगह सेव की गई कक्षाएँ, अध्ययन समय, ट्रांसक्रिप्ट, Smart Notes और संरचित अध्ययन सामग्री देखें।","search.itemDescription":"किसी क्षण को जल्दी खोजने के लिए सेव की गई कक्षाओं में खोजें।","manage.itemDescription":"अपना सेव किया हुआ पाठ इतिहास प्रबंधित करें।","export.itemDescription":"ज़रूरत पड़ने पर अध्ययन नोट्स और सामग्री डाउनलोड करें।","backup.itemDescription":"सेव की गई कक्षाओं का बैकअप निर्यात करें और बाद में पुनर्स्थापित करें।"}
  };
  Object.keys(detailCopy).forEach(function(lang){copy.ui[lang]=Object.assign(copy.ui[lang]||{},detailCopy[lang]);});
  var supportedLanguages = languages.map(function(item){return item[0];});
  languages.forEach(function(item){var code=item[0]; if(!copy[code]) copy[code]=copy.en; if(!copy.ui[code]) copy.ui[code]=copy.ui.en; if(!copy.pages[code]) copy.pages[code]=copy.pages.en;});
  var rtlLanguages = ["ar","fa","he","ur","ps","sd","ku"];
  var languageSelect = document.querySelector(".language-select");
  var savedLanguage = localStorage.getItem("zova-language");
  var currentLanguage = supportedLanguages.indexOf(savedLanguage)>=0 ? savedLanguage : "en";
  if(languageSelect){languageSelect.innerHTML="";languages.forEach(function(item){var option=document.createElement("option");option.value=item[0];option.textContent=item[1];languageSelect.appendChild(option);});}
  function setText(selector, value) { var el=document.querySelector(selector); if(el && value) el.textContent=value; }
  function applyLanguage(lang) {
    if(supportedLanguages.indexOf(lang)<0) lang="en";
    var t=copy[lang] || copy.en; document.documentElement.lang=lang; document.documentElement.dir=rtlLanguages.indexOf(lang)>=0?"rtl":"ltr";
    var ui=Object.assign({},copy.ui.en,copy.ui[lang]||{}); Object.keys(ui).forEach(function(key){document.querySelectorAll('[data-i18n="'+key+'"]').forEach(function(el){el.textContent=ui[key];});});
    var page=Object.assign({},copy.pages.en,copy.pages[lang]||{}); Object.keys(page).forEach(function(key){document.querySelectorAll('[data-i18n="'+key+'"]').forEach(function(el){el.textContent=page[key];});});
    var nav=document.querySelectorAll(".site-nav a"); t.nav.forEach(function(v,i){if(nav[i])nav[i].textContent=v;});
    if(document.querySelector(".hero")){setText(".hero .kicker",t.heroKicker);var title=document.querySelector(".hero h1");if(title){var parts=t.heroTitle.split("|");title.innerHTML=parts[0]+"<br><em>"+parts[1]+"</em>";}setText(".hero .lead",t.heroLead);setText(".hero .note",t.heroNote);setText(".hero .actions .btn.store",t.add);setText(".hero .actions .btn.ghost",t.how);}
    document.querySelectorAll(".btn.store").forEach(function(el){if(el.textContent.trim().indexOf("Add")>=0 || el.textContent.trim().indexOf("Chrome")>=0)el.textContent=t.add;});
    if(languageSelect) languageSelect.value=lang; localStorage.setItem("zova-language",lang);
  }
  if(languageSelect){languageSelect.value=currentLanguage;languageSelect.addEventListener("change",function(){applyLanguage(this.value);});}
  applyLanguage(currentLanguage);

  var themeToggle = document.querySelector(".theme-toggle");
  var savedTheme = localStorage.getItem("zova-theme");
  if (savedTheme === "dark") document.body.classList.add("dark-mode");
  if (themeToggle) {
    var setThemeLabel = function () { themeToggle.textContent = document.body.classList.contains("dark-mode") ? "☀ Light" : "☾ Dark"; };
    setThemeLabel();
    themeToggle.addEventListener("click", function () { var dark = document.body.classList.toggle("dark-mode"); localStorage.setItem("zova-theme", dark ? "dark" : "light"); setThemeLabel(); });
  }

  // Mobile navigation
  var menuBtn = document.querySelector(".menu-btn");
  var nav = document.querySelector(".site-nav");
  if (menuBtn && nav) {
    menuBtn.addEventListener("click", function () {
      var open = nav.classList.toggle("open");
      menuBtn.setAttribute("aria-expanded", open ? "true" : "false");
      menuBtn.textContent = open ? "✕" : "☰";
    });
    nav.querySelectorAll("a").forEach(function (a) {
      a.addEventListener("click", function () {
        nav.classList.remove("open");
        menuBtn.setAttribute("aria-expanded", "false");
        menuBtn.textContent = "☰";
      });
    });
  }

  // Disabled "Coming Soon" store buttons should not jump to top
  document.querySelectorAll('.btn.store[aria-disabled="true"]').forEach(function (a) {
    a.addEventListener("click", function (e) { e.preventDefault(); });
  });

  // Gentle scroll reveal for elements marked .reveal
  var revealEls = document.querySelectorAll(".reveal");
  if ("IntersectionObserver" in window && revealEls.length) {
    var io = new IntersectionObserver(
      function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add("in");
            io.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12, rootMargin: "0px 0px -8% 0px" }
    );
    revealEls.forEach(function (el) { io.observe(el); });
  } else {
    revealEls.forEach(function (el) { el.classList.add("in"); });
  }
})();
